gde_gestion_doc_ecole_homepage:
    path:       /hello-world
    defaults:   { _controller: GdeGestionDocEcoleBundle:Default:index }
gde_gestion_doc_ecole_dbseed:
    path:       /dbseed
    defaults:   { _controller: GdeGestionDocEcoleBundle:Default:dbseed }
gde_gestion_doc_ecole_nouveau_form_d01:
    path:       /nouveau_form_d01
    defaults:   { _controller: GdeGestionDocEcoleBundle:D01:nouveau_form_d01 }
gde_gestion_doc_ecole_table_d01:
    path:       /table_d01
    defaults:   { _controller: GdeGestionDocEcoleBundle:D01:table_d01 }
gde_gestion_doc_ecole_table_d01_json:
    path:       /table_d01_{sort}_{sens}.json
    defaults:   { _controller: GdeGestionDocEcoleBundle:D01:table_d01_json }