gde_gestion_doc_ecole_homepage:
    path:       /hello-world
    defaults:   { _controller: GdeGestionDocEcoleBundle:Default:index }
gde_gestion_doc_ecole_dbseed:
    path:       /dbseed
    defaults:   { _controller: GdeGestionDocEcoleBundle:Default:dbseed }
gde_gestion_doc_ecole_nouveau_form_d01:
    path:       /nouveau_form_d01
    defaults:   { _controller: GdeGestionDocEcoleBundle:D01:nouveau_form_d01 }
gde_gestion_doc_ecole_table_d01:
    path:       /table_d01
    defaults:   { _controller: GdeGestionDocEcoleBundle:D01:table_d01 }
gde_gestion_doc_ecole_table_d01_json:
    path:       /table_d01_{sort}_{sens}.json
    defaults:   { _controller: GdeGestionDocEcoleBundle:D01:table_d01_json }
gde_gestion_doc_ecole_delete_row_d01_json:
    path:       /delete_row_d01_{id}.json
    defaults:   { _controller: GdeGestionDocEcoleBundle:D01:delete_row_d01_json }
gde_gestion_doc_ecole_nouveau_form_d02:
    path:       /nouveau_form_d02
    defaults:   { _controller: GdeGestionDocEcoleBundle:D02:nouveau_form_d02 }
gde_gestion_doc_ecole_table_d02:
    path:       /table_d02
    defaults:   { _controller: GdeGestionDocEcoleBundle:D02:table_d02 }
gde_gestion_doc_ecole_table_d02_json:
    path:       /table_d02_{sort}_{sens}.json
    defaults:   { _controller: GdeGestionDocEcoleBundle:D02:table_d02_json }
gde_gestion_doc_ecole_delete_row_d02_json:
    path:       /delete_row_d02_{id}.json
    defaults:   { _controller: GdeGestionDocEcoleBundle:D02:delete_row_d02_json }
gde_gestion_doc_ecole_nouveau_form_d03:
    path:       /nouveau_form_d03
    defaults:   { _controller: GdeGestionDocEcoleBundle:D03:nouveau_form_d03 }
gde_gestion_doc_ecole_table_d03:
    path:       /table_d03
    defaults:   { _controller: GdeGestionDocEcoleBundle:D03:table_d03 }
gde_gestion_doc_ecole_table_d03_json:
    path:       /table_d03_{sort}_{sens}.json
    defaults:   { _controller: GdeGestionDocEcoleBundle:D03:table_d03_json }
gde_gestion_doc_ecole_delete_row_d03_json:
    path:       /delete_row_d03_{id}.json
    defaults:   { _controller: GdeGestionDocEcoleBundle:D03:delete_row_d03_json }
gde_gestion_doc_ecole_nouveau_form_d04:
    path:       /nouveau_form_d04
    defaults:   { _controller: GdeGestionDocEcoleBundle:D04:nouveau_form_d04 }
gde_gestion_doc_ecole_table_d04:
    path:       /table_d04
    defaults:   { _controller: GdeGestionDocEcoleBundle:D04:table_d04 }
gde_gestion_doc_ecole_table_d04_json:
    path:       /table_d04_{sort}_{sens}.json
    defaults:   { _controller: GdeGestionDocEcoleBundle:D04:table_d04_json }
gde_gestion_doc_ecole_delete_row_d04_json:
    path:       /delete_row_d04_{id}.json
    defaults:   { _controller: GdeGestionDocEcoleBundle:D04:delete_row_d03_json }